# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smm_fit_bridge <- function(input, y, family, options, family_options, beta0 = NULL, solver = -1L, jacobi = TRUE, krylov_rtol = 1e-4, krylov_atol = 1e-8, intercept = TRUE, penalize_intercept = FALSE, inference = 1L, inference_max_p = 50L, cov_type = 0L, dispersion = NA_real_, capture_trace = FALSE) {
    .Call(`_SpectralMM_smm_fit_bridge`, input, y, family, options, family_options, beta0, solver, jacobi, krylov_rtol, krylov_atol, intercept, penalize_intercept, inference, inference_max_p, cov_type, dispersion, capture_trace)
}
