// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// smm_fit_bridge
List smm_fit_bridge(SEXP input, NumericVector y, int family, List options, List family_options, Nullable<NumericVector> beta0, int solver, bool jacobi, double krylov_rtol, double krylov_atol, bool intercept, bool penalize_intercept, int inference, int inference_max_p, int cov_type, double dispersion, bool capture_trace);
RcppExport SEXP _SpectralMM_smm_fit_bridge(SEXP inputSEXP, SEXP ySEXP, SEXP familySEXP, SEXP optionsSEXP, SEXP family_optionsSEXP, SEXP beta0SEXP, SEXP solverSEXP, SEXP jacobiSEXP, SEXP krylov_rtolSEXP, SEXP krylov_atolSEXP, SEXP interceptSEXP, SEXP penalize_interceptSEXP, SEXP inferenceSEXP, SEXP inference_max_pSEXP, SEXP cov_typeSEXP, SEXP dispersionSEXP, SEXP capture_traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type family(familySEXP);
    Rcpp::traits::input_parameter< List >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< List >::type family_options(family_optionsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< int >::type solver(solverSEXP);
    Rcpp::traits::input_parameter< bool >::type jacobi(jacobiSEXP);
    Rcpp::traits::input_parameter< double >::type krylov_rtol(krylov_rtolSEXP);
    Rcpp::traits::input_parameter< double >::type krylov_atol(krylov_atolSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type penalize_intercept(penalize_interceptSEXP);
    Rcpp::traits::input_parameter< int >::type inference(inferenceSEXP);
    Rcpp::traits::input_parameter< int >::type inference_max_p(inference_max_pSEXP);
    Rcpp::traits::input_parameter< int >::type cov_type(cov_typeSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< bool >::type capture_trace(capture_traceSEXP);
    rcpp_result_gen = Rcpp::wrap(smm_fit_bridge(input, y, family, options, family_options, beta0, solver, jacobi, krylov_rtol, krylov_atol, intercept, penalize_intercept, inference, inference_max_p, cov_type, dispersion, capture_trace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpectralMM_smm_fit_bridge", (DL_FUNC) &_SpectralMM_smm_fit_bridge, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpectralMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
