#!/usr/bin/env python3
"""Stage or build the independent R/, python/ and julia/ packages."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
from sync_package_sources import sync

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = {'R': 'R', 'Python': 'python', 'Julia': 'julia'}
MARKER = '.spectralmm-generated'


def version():
    versions = [re.search(pattern, (ROOT / name).read_text()).group(1)
                for name, pattern in [('R/DESCRIPTION', r'(?m)^Version: (\S+)'),
                                      ('julia/Project.toml', r'(?m)^version = "([^"]+)"'),
                                      ('python/pyproject.toml', r'(?m)^version = "([^"]+)"')]]
    if len(set(versions)) != 1:
        raise RuntimeError('R, Python and Julia versions must match before packaging')
    return versions[0]


def assemble(output, language, release):
    sync(check=True)
    container = output / language
    if container.exists() and (container.is_symlink() or not (container / MARKER).is_file()):
        raise RuntimeError(f'Refusing to overwrite an unmarked directory: {container}')
    container.mkdir(parents=True, exist_ok=True)
    (container / MARKER).write_text('Generated by tools/build_packages.py\n')
    destination = container / 'SpectralMM'
    if destination.is_symlink():
        raise RuntimeError(f'Refusing to replace a symbolic link: {destination}')
    with tempfile.TemporaryDirectory(prefix='.stage-', dir=container) as work:
        stage = Path(work) / 'SpectralMM'
        shutil.copytree(ROOT / LANGUAGES[language], stage,
            ignore=shutil.ignore_patterns('Manifest.toml', '__pycache__', '*.pyc',
                '.DS_Store', '.ipynb_checkpoints', '*.ipynb', 'build', 'dist', '*.egg-info',
                '*.o', '*.so', '*.dylib', '*.dll', '*.cov', 'build.log', '*.Rcheck', '*.tar.gz'))
        hashes = {str(p.relative_to(stage)): hashlib.sha256(p.read_bytes()).hexdigest()
                  for p in sorted(stage.rglob('*')) if p.is_file()}
        if destination.exists():
            shutil.rmtree(destination)
        shutil.move(str(stage), destination)
    (container / 'source-manifest.json').write_text(json.dumps(
        dict(language=language, version=release, files=hashes), indent=2) + '\n')
    print(f'{language}: {destination}', flush=True)
    return destination


def build(package, language):
    artifacts = package.parent / 'artifacts'
    artifacts.mkdir(exist_ok=True)
    if language == 'R':
        subprocess.run(['R', 'CMD', 'build', str(package)], cwd=artifacts, check=True)
    elif language == 'Python':
        subprocess.run([sys.executable, '-m', 'build', '--outdir', str(artifacts), str(package)], check=True)
    else:
        import tarfile
        with tarfile.open(artifacts / f'SpectralMM_{version()}.tar.gz', 'w:gz') as tar:
            tar.add(package, arcname='SpectralMM')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--language', choices=['all', *LANGUAGES], default='all')
    parser.add_argument('--output', type=Path, default=ROOT / 'dist')
    parser.add_argument('--build', action='store_true')
    args = parser.parse_args()
    for language in LANGUAGES if args.language == 'all' else (args.language,):
        package = assemble(args.output.expanduser().resolve(), language, version())
        if args.build:
            build(package, language)


if __name__ == '__main__':
    main()
